"""Estimator public enums, results, options, constants, and typed errors."""

from estimator.core.constants import (
    DEFAULT_MAX_CRAB_ANGLE_DEG,
    DEFAULT_MIN_GROUNDSPEED_MPS,
    EPS_DISTANCE_M,
)
from estimator.core.enums import (
    EnergyPowerSource,
    EstimateStatus,
    FailureCode,
    FailureKind,
    GeofenceKind,
    LegPhase,
    SpeedSource,
    WarningCode,
)
from estimator.core.errors import (
    EstimatorError,
    EstimatorInfeasibleError,
    InvalidEstimatorInputError,
    UnsupportedEstimatorFeatureError,
)
from estimator.core.geofence import (
    GeofenceCoordinate,
    GeofenceGeometry,
    GeofencePolygon,
    GeofenceRecurrence,
    GeofenceZone,
)
from estimator.core.landing_zone import (
    LandingZone,
    LandingZoneCoordinate,
    LandingZoneGeometry,
    LandingZonePolygon,
)
from estimator.core.obstacle import (
    Obstacle,
    ObstacleCoordinate,
    ObstacleGeometry,
    ObstacleGeometryType,
    ObstaclePolygon,
)
from estimator.core.options import EstimationOptions
from estimator.core.results import (
    EnergyEstimate,
    EnergyLegEstimate,
    EstimatorFailure,
    EstimatorWarning,
    GeofenceConflict,
    GeofenceEstimate,
    GroundRiskEstimate,
    GroundRiskLegEstimate,
    LandingZoneEstimate,
    LandingZoneStateReachability,
    LegEstimate,
    LinkEstimate,
    LinkSystemEstimate,
    MissionEstimate,
    ObstacleClearanceViolation,
    ObstacleEstimate,
    ResourceEstimate,
    ResourceSystemEstimate,
    RthReserveTimelinePoint,
    WindVector,
)

__all__ = [
    "DEFAULT_MAX_CRAB_ANGLE_DEG",
    "DEFAULT_MIN_GROUNDSPEED_MPS",
    "EPS_DISTANCE_M",
    "EnergyEstimate",
    "EnergyLegEstimate",
    "EnergyPowerSource",
    "EstimateStatus",
    "EstimationOptions",
    "EstimatorError",
    "EstimatorFailure",
    "EstimatorInfeasibleError",
    "EstimatorWarning",
    "FailureCode",
    "FailureKind",
    "GeofenceConflict",
    "GeofenceCoordinate",
    "GeofenceEstimate",
    "GroundRiskEstimate",
    "GroundRiskLegEstimate",
    "GeofenceGeometry",
    "GeofenceKind",
    "GeofencePolygon",
    "GeofenceRecurrence",
    "GeofenceZone",
    "InvalidEstimatorInputError",
    "LandingZone",
    "LandingZoneCoordinate",
    "LandingZoneEstimate",
    "LandingZoneGeometry",
    "LandingZonePolygon",
    "LandingZoneStateReachability",
    "LegPhase",
    "LegEstimate",
    "LinkEstimate",
    "LinkSystemEstimate",
    "MissionEstimate",
    "Obstacle",
    "ObstacleClearanceViolation",
    "ObstacleCoordinate",
    "ObstacleEstimate",
    "ObstacleGeometry",
    "ObstacleGeometryType",
    "ObstaclePolygon",
    "ResourceEstimate",
    "ResourceSystemEstimate",
    "RthReserveTimelinePoint",
    "SpeedSource",
    "UnsupportedEstimatorFeatureError",
    "WarningCode",
    "WindVector",
]
