"""Public estimator enums."""

from enum import StrEnum


class FidelityMode(StrEnum):
    """Estimator fidelity level.

    V1 is the original leg-to-leg geodesic model.
    V2 adds turn-arc geometry at waypoints and fixed-wing circular loiter.
    """

    V1 = "v1"
    V2 = "v2"


class EstimateStatus(StrEnum):
    SUCCESS = "success"
    INFEASIBLE = "infeasible"
    ERROR = "error"


class FailureKind(StrEnum):
    UNSUPPORTED = "unsupported"
    INVALID_INPUT = "invalid_input"
    INFEASIBLE = "infeasible"


class FailureCode(StrEnum):
    UNSUPPORTED_ALTITUDE_REFERENCE_TERRAIN = "UNSUPPORTED_ALTITUDE_REFERENCE_TERRAIN"
    TERRAIN_COVERAGE_MISSING = "TERRAIN_COVERAGE_MISSING"
    POPULATION_COVERAGE_MISSING = "POPULATION_COVERAGE_MISSING"
    SORA_INPUT_UNSUPPORTED = "SORA_INPUT_UNSUPPORTED"
    UNSUPPORTED_LOITER_FOR_VEHICLE_CLASS = "UNSUPPORTED_LOITER_FOR_VEHICLE_CLASS"
    MISSING_REQUIRED_SPEED_PROFILE = "MISSING_REQUIRED_SPEED_PROFILE"
    INVALID_SPEED_PROFILE = "INVALID_SPEED_PROFILE"
    INVALID_ENERGY_MODEL = "INVALID_ENERGY_MODEL"
    INVALID_ENERGY_POLICY = "INVALID_ENERGY_POLICY"
    INVALID_MISSION_PROFILE = "INVALID_MISSION_PROFILE"
    WIND_TRIANGLE_NO_SOLUTION = "WIND_TRIANGLE_NO_SOLUTION"
    CRAB_ANGLE_LIMIT_EXCEEDED = "CRAB_ANGLE_LIMIT_EXCEEDED"
    GROUNDSPEED_NON_POSITIVE = "GROUNDSPEED_NON_POSITIVE"
    GROUNDSPEED_BELOW_MIN = "GROUNDSPEED_BELOW_MIN"
    STATION_KEEP_INFEASIBLE_WIND = "STATION_KEEP_INFEASIBLE_WIND"
    INSUFFICIENT_ENERGY = "INSUFFICIENT_ENERGY"
    RESERVE_BELOW_THRESHOLD = "RESERVE_BELOW_THRESHOLD"
    RTH_RESERVE_BELOW_THRESHOLD = "RTH_RESERVE_BELOW_THRESHOLD"
    MISSING_ENERGY_MODEL = "MISSING_ENERGY_MODEL"
    UNSUPPORTED_PHASE_ENERGY_MODEL = "UNSUPPORTED_PHASE_ENERGY_MODEL"
    RESOURCE_FEASIBILITY_FAILED = "RESOURCE_FEASIBILITY_FAILED"
    LINK_FEASIBILITY_FAILED = "LINK_FEASIBILITY_FAILED"
    ROUTE_ENTERS_FORBIDDEN_ZONE = "ROUTE_ENTERS_FORBIDDEN_ZONE"
    ROUTE_EXITS_REQUIRED_ZONE = "ROUTE_EXITS_REQUIRED_ZONE"
    ASSET_LOAD_ERROR = "ASSET_LOAD_ERROR"
    INVALID_GEOMETRY = "INVALID_GEOMETRY"
    UNSUPPORTED_GEOMETRY_TYPE = "UNSUPPORTED_GEOMETRY_TYPE"
    NO_REACHABLE_LANDING_ZONE = "NO_REACHABLE_LANDING_ZONE"
    LANDING_ZONE_REACHABLE_BUT_BELOW_RESERVE = (
        "LANDING_ZONE_REACHABLE_BUT_BELOW_RESERVE"
    )
    UNSUPPORTED_LANDING_ZONE_GEOMETRY = "UNSUPPORTED_LANDING_ZONE_GEOMETRY"
    ALL_LANDING_ZONES_UNAVAILABLE = "ALL_LANDING_ZONES_UNAVAILABLE"
    WIND_LIMIT_EXCEEDED = "WIND_LIMIT_EXCEEDED"
    GUST_LIMIT_EXCEEDED = "GUST_LIMIT_EXCEEDED"
    CROSSWIND_LIMIT_EXCEEDED = "CROSSWIND_LIMIT_EXCEEDED"
    WEATHER_DATA_UNAVAILABLE = "WEATHER_DATA_UNAVAILABLE"
    OBSTACLE_CLEARANCE_VIOLATED = "OBSTACLE_CLEARANCE_VIOLATED"
    TERRAIN_CLEARANCE_VIOLATED = "TERRAIN_CLEARANCE_VIOLATED"


class WarningCode(StrEnum):
    LOITER_ASSUMED_ZERO_GROUND_DISTANCE = "LOITER_ASSUMED_ZERO_GROUND_DISTANCE"
    HOVER_SPEED_USED_AS_STATION_KEEP_AUTHORITY = (
        "HOVER_SPEED_USED_AS_STATION_KEEP_AUTHORITY"
    )
    LOW_GROUNDSPEED_MARGIN = "LOW_GROUNDSPEED_MARGIN"
    HIGH_CRAB_MARGIN = "HIGH_CRAB_MARGIN"
    MAX_WIND_EXCEEDED = "MAX_WIND_EXCEEDED"
    RESERVE_BELOW_FAILSAFE_WARN_THRESHOLD = "RESERVE_BELOW_FAILSAFE_WARN_THRESHOLD"
    RESERVE_BELOW_FAILSAFE_ABORT_THRESHOLD = "RESERVE_BELOW_FAILSAFE_ABORT_THRESHOLD"
    LOITER_RADIUS_IGNORED = "LOITER_RADIUS_IGNORED"
    ROUTE_ACTIONS_AFTER_RTL = "ROUTE_ACTIONS_AFTER_RTL"
    GEOFENCE_EVALUATED_2D_ONLY = "GEOFENCE_EVALUATED_2D_ONLY"
    GEOFENCE_ZERO_ZONES = "GEOFENCE_ZERO_ZONES"
    DEPARTURE_TIME_MISSING = "DEPARTURE_TIME_MISSING"
    DIVERT_ENERGY_TAS_ONLY = "DIVERT_ENERGY_TAS_ONLY"
    ENERGY_REFERENCE_CONDITIONS_MISSING = "ENERGY_REFERENCE_CONDITIONS_MISSING"
    POPULATION_DENSITY_DIMENSION_MISSING = "POPULATION_DENSITY_DIMENSION_MISSING"
    GUST_DATA_UNAVAILABLE = "GUST_DATA_UNAVAILABLE"


class LegPhase(StrEnum):
    VERTICAL_TAKEOFF = "vertical_takeoff"
    TRANSIT = "transit"
    TURN_ARC = "turn_arc"
    LOITER_TRANSIT = "loiter_transit"
    LOITER_DWELL = "loiter_dwell"
    LANDING_TRANSIT = "landing_transit"
    RTL_TRANSIT = "rtl_transit"


class CapabilitySource(StrEnum):
    EXPLICIT = "explicit"
    DERIVED_FROM_VEHICLE_CLASS = "derived_from_vehicle_class"


class OptionSource(StrEnum):
    RUNTIME_OPTIONS = "runtime_options"
    MISSION_ESTIMATION = "mission_estimation"
    LIBRARY_DEFAULTS = "library_defaults"


class SpeedSource(StrEnum):
    VEHICLE_CRUISE_SPEED = "vehicle.cruise_speed_mps"
    MISSION_DEFAULT_CRUISE_SPEED = "mission.defaults.cruise_speed_mps"
    VEHICLE_HOVER_SPEED = "vehicle.hover_speed_mps"
    VEHICLE_MAX_STATION_KEEP_WIND = "vehicle.max_station_keep_wind_mps"
    STATION_KEEP_AUTHORITY = "station_keep_authority"
    NONE = "none"


class EnergyPowerSource(StrEnum):
    CRUISE_POWER = "vehicle.energy.cruise_power_w"
    HOVER_POWER = "vehicle.energy.hover_power_w"
    CLIMB_POWER = "vehicle.energy.climb_power_w"
    DESCENT_POWER = "vehicle.energy.descent_power_w"


class GeofenceKind(StrEnum):
    FORBIDDEN = "forbidden"
    REQUIRED = "required"


class AssertionOutcome(StrEnum):
    PASSED = "passed"
    FAILED = "failed"
    SKIPPED = "skipped"
    UNSUPPORTED = "unsupported"


class ScenarioStatus(StrEnum):
    PASSED = "passed"
    FAILED = "failed"
    ERROR = "error"
